@echo off
setlocal enabledelayedexpansion
title TeleDrive Windows Installer Builder

echo.
echo ========================================
echo    TeleDrive Windows Installer Builder
echo ========================================
echo.

set "PROJECT_DIR=%~dp0"
if "%PROJECT_DIR:~-1%"=="\" set "PROJECT_DIR=%PROJECT_DIR:~0,-1%"

:: ============================================
:: CHECK REQUIREMENTS
:: ============================================

echo [1/5] Kiem tra yeu cau...

:: Check Inno Setup
set "ISCC="
if exist "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" (
    set "ISCC=C:\Program Files (x86)\Inno Setup 6\ISCC.exe"
) else if exist "C:\Program Files\Inno Setup 6\ISCC.exe" (
    set "ISCC=C:\Program Files\Inno Setup 6\ISCC.exe"
) else if exist "C:\Program Files (x86)\Inno Setup 5\ISCC.exe" (
    set "ISCC=C:\Program Files (x86)\Inno Setup 5\ISCC.exe"
)

if "%ISCC%"=="" (
    echo [ERROR] Inno Setup khong duoc cai dat!
    echo.
    echo Vui long tai va cai dat Inno Setup tu:
    echo https://jrsoftware.org/isdl.php
    echo.
    pause
    exit /b 1
)
echo [OK] Inno Setup

:: Check if portable exe exists
if not exist "%PROJECT_DIR%\release\TeleDrive-Portable.exe" (
    echo [INFO] Portable exe chua co, dang build...
    call "%PROJECT_DIR%\portable.bat"
    if errorlevel 1 (
        echo [ERROR] Build portable that bai!
        pause
        exit /b 1
    )
)
echo [OK] TeleDrive-Portable.exe

echo.

:: ============================================
:: CREATE INNO SETUP SCRIPT
:: ============================================

echo [2/5] Tao Inno Setup script...

set "ISS_FILE=%PROJECT_DIR%\teledrive-setup.iss"

(
echo ; TeleDrive Windows Installer Script
echo ; Auto-generated by installer.bat
echo.
echo #define MyAppName "TeleDrive"
echo #define MyAppVersion "1.0.0"
echo #define MyAppPublisher "TeleDrive"
echo #define MyAppURL "https://github.com/quangminh1212/TeleDrive"
echo #define MyAppExeName "TeleDrive.exe"
echo.
echo [Setup]
echo AppId={{A1B2C3D4-E5F6-7890-ABCD-EF1234567890}
echo AppName={#MyAppName}
echo AppVersion={#MyAppVersion}
echo AppPublisher={#MyAppPublisher}
echo AppPublisherURL={#MyAppURL}
echo AppSupportURL={#MyAppURL}
echo AppUpdatesURL={#MyAppURL}
echo DefaultDirName={autopf}\{#MyAppName}
echo DefaultGroupName={#MyAppName}
echo AllowNoIcons=yes
echo LicenseFile=
echo PrivilegesRequired=admin
echo OutputDir=%PROJECT_DIR%\release
echo OutputBaseFilename=TeleDrive-Setup
echo SetupIconFile=%PROJECT_DIR%\frontend\src-tauri\icons\icon.ico
echo Compression=lzma2/ultra64
echo SolidCompression=yes
echo WizardStyle=modern
echo UninstallDisplayIcon={app}\{#MyAppExeName}
echo.
echo [Languages]
echo Name: "english"; MessagesFile: "compiler:Default.isl"
echo.
echo [Tasks]
echo Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
echo Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked; OnlyBelowVersion: 6.1; Check: not IsAdminInstallMode
echo.
echo [Files]
echo Source: "%PROJECT_DIR%\release\TeleDrive-Portable.exe"; DestDir: "{app}"; DestName: "{#MyAppExeName}"; Flags: ignoreversion
echo.
echo [Icons]
echo Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
echo Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
echo Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
echo Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: quicklaunchicon
echo.
echo [Run]
echo Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
echo.
echo [UninstallDelete]
echo Type: filesandordirs; Name: "{localappdata}\TeleDrive"
) > "%ISS_FILE%"

echo [OK] Created teledrive-setup.iss

echo.

:: ============================================
:: BUILD INSTALLER
:: ============================================

echo [3/5] Build Windows Installer...
echo (Co the mat 1-2 phut...)
echo.

"%ISCC%" "%ISS_FILE%"

if errorlevel 1 (
    echo [ERROR] Inno Setup build that bai!
    pause
    exit /b 1
)

echo.
echo [OK] Build installer thanh cong!

:: ============================================
:: CLEANUP
:: ============================================

echo.
echo [4/5] Cleanup...

del "%ISS_FILE%" 2>nul
echo [OK] Removed temporary files

:: ============================================
:: SHOW RESULT
:: ============================================

echo.
echo [5/5] Ket qua...
echo.

set "OUTPUT=%PROJECT_DIR%\release\TeleDrive-Setup.exe"
if exist "%OUTPUT%" (
    echo ========================================
    echo         INSTALLER BUILD COMPLETE!
    echo ========================================
    echo.
    echo File: %OUTPUT%
    echo.
    for %%A in ("%OUTPUT%") do (
        set "SIZE=%%~zA"
        set /a "SIZE_MB=!SIZE!/1048576"
        echo Size: !SIZE_MB! MB
    )
    echo.
    echo Installer se cai dat TeleDrive vao Program Files
    echo va tao shortcut tren Desktop.
    echo.
    explorer /select,"%OUTPUT%"
) else (
    echo [ERROR] Khong tim thay output file!
)

echo.
pause
