[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "teledrive"
version = "1.0.0"
description = "Modern Telegram File Manager with Windows Explorer-style interface"
readme = "README.md"
license = {text = "MIT"}
authors = [
    {name = "TeleDrive Team", email = "contact@teledrive.dev"}
]
maintainers = [
    {name = "TeleDrive Team", email = "contact@teledrive.dev"}
]
keywords = ["telegram", "file-manager", "web-app", "flask", "file-organization"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Communications :: Chat",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
    "Topic :: System :: Archiving",
    "Framework :: Flask",
]
requires-python = ">=3.8"
dependencies = [
    "telethon>=1.34.0",
    "pandas>=2.0.0",
    "tqdm>=4.65.0",
    "python-dotenv>=1.0.0",
    "aiofiles>=23.0.0",
    "openpyxl>=3.1.0",
    "flask>=2.3.3,<3.0.0",
    "flask-cors>=4.0.0",
    "flask-login>=0.6.3",
    "flask-sqlalchemy>=3.0.5",
    "sqlalchemy>=1.4.53,<2.0.0",
    "pillow>=10.0.0",
    "python-magic>=0.4.27",
    "redis>=4.0.0",
    "psutil>=5.9.0",
    "waitress>=2.1.0",
    "gunicorn>=21.0.0",
    "cryptography>=41.0.0",
    "pydantic>=2.0.0",
    "click>=8.0.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
    "pytest-asyncio>=0.21.0",
    "black>=23.0.0",
    "isort>=5.12.0",
    "flake8>=6.0.0",
    "mypy>=1.5.0",
    "pre-commit>=3.0.0",
    "bandit>=1.7.0",
    "safety>=2.3.0",
]
test = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
    "pytest-asyncio>=0.21.0",
    "pytest-mock>=3.11.0",
    "httpx>=0.24.0",
]
docs = [
    "sphinx>=7.0.0",
    "sphinx-rtd-theme>=1.3.0",
    "sphinx-autodoc-typehints>=1.24.0",
    "myst-parser>=2.0.0",
]
production = [
    "gunicorn>=21.0.0",
    "psycopg2-binary>=2.9.0",
    "sentry-sdk[flask]>=1.32.0",
]

[project.urls]
Homepage = "https://github.com/quangminh1212/TeleDrive"
Documentation = "https://github.com/quangminh1212/TeleDrive/docs"
Repository = "https://github.com/quangminh1212/TeleDrive.git"
"Bug Tracker" = "https://github.com/quangminh1212/TeleDrive/issues"
Changelog = "https://github.com/quangminh1212/TeleDrive/blob/main/CHANGELOG.md"

[project.scripts]
teledrive = "teledrive.cli:main"
teledrive-web = "teledrive.web:main"
teledrive-scanner = "teledrive.scanner:main"

[tool.setuptools.packages.find]
where = ["src"]
include = ["teledrive*"]

[tool.setuptools.package-dir]
"" = "src"

# Black configuration
[tool.black]
line-length = 88
target-version = ['py38', 'py39', 'py310', 'py311', 'py312']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
  | migrations
)/
'''

# isort configuration
[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88
known_first_party = ["teledrive"]
known_third_party = ["flask", "telethon", "pandas", "sqlalchemy"]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]

# MyPy configuration
[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
strict_equality = true
show_error_codes = true

[[tool.mypy.overrides]]
module = [
    "telethon.*",
    "python_magic.*",
    "psutil.*",
    "tqdm.*",
]
ignore_missing_imports = true

# Pytest configuration
[tool.pytest.ini_options]
minversion = "7.0"
addopts = [
    "--strict-markers",
    "--strict-config",
    "--cov=teledrive",
    "--cov-report=term-missing",
    "--cov-report=html",
    "--cov-report=xml",
    "--cov-fail-under=80",
]
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "integration: marks tests as integration tests",
    "unit: marks tests as unit tests",
]

# Coverage configuration
[tool.coverage.run]
source = ["src/teledrive"]
omit = [
    "*/tests/*",
    "*/migrations/*",
    "*/venv/*",
    "*/env/*",
    "*/__pycache__/*",
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if self.debug:",
    "if settings.DEBUG",
    "raise AssertionError",
    "raise NotImplementedError",
    "if 0:",
    "if __name__ == .__main__.:",
    "class .*\\bProtocol\\):",
    "@(abc\\.)?abstractmethod",
]

# Bandit security linter configuration
[tool.bandit]
exclude_dirs = ["tests", "migrations"]
skips = ["B101", "B601"]

# Flake8 configuration (in setup.cfg since flake8 doesn't support pyproject.toml yet)
