[build-system]
requires = ["setuptools>=42.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "teledrive"
version = "1.0.0"
description = "Modern file management for Telegram files with Google Drive-style interface"
readme = "README.md"
authors = [
    {name = "TeleDrive Team", email = "contact@teledrive.dev"}
]
license = {text = "MIT"}
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Communications :: File Sharing",
    "Topic :: Utilities",
    "Framework :: Flask"
]

dependencies = [
    "Flask>=2.0.0",
    "Flask-SQLAlchemy>=3.0.0",
    "Flask-Login>=0.6.0",
    "Flask-WTF>=1.1.0",
    "Telethon>=1.26.0",
    "SQLAlchemy>=2.0.0",
    "python-dotenv>=0.21.0",
    "pillow>=9.3.0",
    "openpyxl>=3.0.10",
    "pandas>=1.5.0",
    "cryptography>=38.0.0",
    "werkzeug>=2.2.0",
    "jinja2>=3.1.0",
    "requests>=2.28.0",
    "pydantic>=1.10.0"
]

[project.optional-dependencies]
dev = [
    "black>=23.1.0",
    "flake8>=6.0.0",
    "isort>=5.12.0",
    "mypy>=1.0.0",
    "pytest>=7.2.0",
    "pytest-cov>=4.0.0",
    "pre-commit>=3.0.0",
    "bandit>=1.7.0",
]

production = [
    "gunicorn>=20.1.0",
    "gevent>=22.10.0",
    "psycopg2-binary>=2.9.0",
    "uvicorn>=0.20.0",
]

[project.urls]
"Homepage" = "https://github.com/quangminh1212/TeleDrive"
"Bug Tracker" = "https://github.com/quangminh1212/TeleDrive/issues"
"Documentation" = "https://github.com/quangminh1212/TeleDrive/wiki"

[tool.black]
line-length = 88
target-version = ["py38", "py39", "py310"]
include = '\.pyi?$'

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true

[[tool.mypy.overrides]]
module = "tests.*"
disallow_untyped_defs = false
disallow_incomplete_defs = false

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
pythonpath = ["."]
