"""
TeleDrive version information.
"""

# This file is auto-generated by setuptools_scm
# When distributing the package, this file will be replaced with a version based on Git tags
__version__ = "1.0.0" 